name: workflow for training the model
on:
  pull_request:
    types: [closed]
jobs:
 build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.16
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint
    - name: Black
      run: |
        make format
    - name: Train
      run: |
        make trainmodel
